// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzi4I0KuDicAXHygNY1BPCTp4hcTRv9Rs',
    appId: '1:923546555708:web:d3927826f1981a187dba39',
    messagingSenderId: '923546555708',
    projectId: 'the-library-b07f0',
    authDomain: 'the-library-b07f0.firebaseapp.com',
    storageBucket: 'the-library-b07f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuODVuCgQStfbtyxHkCod17UtsUNTynLw',
    appId: '1:923546555708:android:a8b7002d2e2c1f8c7dba39',
    messagingSenderId: '923546555708',
    projectId: 'the-library-b07f0',
    storageBucket: 'the-library-b07f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyidbY9VGDhn1qHyHhsGZByfCu3cUNR0',
    appId: '1:923546555708:ios:fd15d19c6f6d8f257dba39',
    messagingSenderId: '923546555708',
    projectId: 'the-library-b07f0',
    storageBucket: 'the-library-b07f0.appspot.com',
    iosBundleId: 'com.thelibrary.theLibrary',
  );
}
